module.exports = (grunt)->
  grunt.initConfig
    pkg: grunt.file.readJSON 'package.json'

    # copy stuff to build folder
    copy:
      html:
        files: [
          expand: true
          src: './*.html'
          dest: './build/'
        ]
      css:
        files: [
          expand: true
          # copy styles except admin.css
          # which is generated by sass: task
          src: ['css/**/*.css', '!css/admin.css']
          dest: './build/'
        ]
      fonts:
        files: [
          expand: true
          src: 'fonts/**/*.*'
          dest: './build/'
        ]
      icons:
        files: [
          expand: true
          src: 'icons/**/*.*'
          dest: './build/'
        ]



    sass:
      dev:
        options:
          style: 'expanded'
        expand: true
        cwd: './scss'
        src: ['*.scss', '**/*.scss', '!bootstrap/bootstrap.scss']
        dest: './css/'
        ext: '.css'

      build:
        options:
          style: 'compressed'
        expand: true
        cwd: './scss'
        src: ['*.scss', '**/*.scss']
        dest: './build/css/'
        ext: '.css'



    coffee: 
      compile: 
        files: {"js/admin.js": "js/admin.coffee"}



    uglify:
      options:
        mangle: false
        report: 'gzip'
      scripts:
        files: [
          expand: true
          cwd: 'js/'
          # uglify files and copy to build
          # except admin.js which is copied by coffer task
          src: ['**/*.js', '!./admin.js']
          dest: 'build/js'
        ]
          


    imagemin:
      options: { optimizationLevel: 3 }

      images: 
        files: [
          expand: true
          cwd: './images/'
          src: ['**/*.{png,jpg,gif}']
          dest: './build/images/'
        ]
      avatars:
        files: [
          expand: true
          cwd: './placeholders/avatars/'
          src: ['**/*.{png,jpg,gif}']
          dest: './build/placeholders/avatars/'
        ]
      photos:
        files: [
          expand: true
          cwd: './placeholders/photos/'
          src: ['**/*.{png,jpg,gif}']
          dest: './build/placeholders/photos/'
        ]
      backgrounds:
        files: [
          expand: true
          cwd: './backgrounds/'
          src: ['**/*.{png,jpg,gif}']
          dest: './build/backgrounds/'
        ]


    coffee_jshint:
      files: ['js/*coffee']
      options:
        reporter: require('jshint-stylish')
        globals: ['$', 'console', 'moment', 'Morris', 'document', 'setTimeout', 'mina', 'Snap', 'Dropzone']


    browser_sync:
      files:
        src: ['css/*.css', 'images/*.{jpg,png,gif}', '*.html', 'js/*.js']
      options:
        debugInfo: true
        watchTask: true
        server:
          baseDir: '.'
        ghostMode:
          scroll: true
          links: true
          forms: true


    watch:
      styles:
        files: ["scss/*.scss", 'scss/*/*.scss']
        tasks: ['sass']
      scrips:
        files: ["js/*.coffee"]
        tasks: ["coffee"]


    connect:
      server:
        options:
          port: 8000
          base: './'

  require('load-grunt-tasks')(grunt)

  grunt.registerTask 'dev', ['sass:dev', 'coffee', 'coffee_jshint', 'browser_sync', 'watch']
  grunt.registerTask 'build', ['sass:build', 'uglify', 'copy', 'imagemin']
